In [ ]:
#Data Cleaning

In [1]:
import pandas as pd

In [4]:
import os
os.getcwd()

'C:\\Data'

In [5]:
df= pd.read_csv(r"C:\Data\fraudTest.csv\CleanFraudTest.csv")

In [6]:
df.head(5)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,Hour
0,6/22/2020 13:42,4.900000e+18,fraud_Johnston-Casper,travel,1.0,Randy,Wood,M,542 Howe Mission Apt. 092,Port Richey,...,-82.6927,42619,Environmental education officer,10/7/1975,702d4af26c7e9e7311b8f1b774955481,1371908573,28.745893,-83.478989,0,13
1,6/22/2020 15:57,4.190000e+15,"fraud_Langworth, Boehm and Gulgowski",shopping_net,1.0,Jennifer,Spencer,F,477 Wheeler Burg,Amanda,...,-82.7552,4512,Farm manager,10/3/1992,b468beb46ee3bbebd43e962ecca733d1,1371916667,40.235605,-82.232475,0,15
2,6/22/2020 19:49,5.710000e+11,"fraud_Kuhic, Bins and Pfeffer",shopping_net,1.0,Barbara,Taylor,F,0069 Robin Brooks Apt. 695,Elberta,...,-86.2141,372,"Exhibitions officer, museum/gallery",7/12/1995,0e5e5a49757d0804c928da89403ad8b3,1371930559,44.717170,-86.940090,0,19
3,6/29/2020 14:31,4.560000e+18,fraud_Gerlach Inc,shopping_net,1.0,Stacy,Villegas,F,20581 Pena Walks,Colorado Springs,...,-104.6556,525713,Museum/gallery exhibitions officer,5/9/1992,3b5f03ac38b6257566e31957f3f959ea,1372516297,38.037407,-105.247202,0,14
4,6/29/2020 18:37,3.400000e+14,fraud_Rolfson-Kunde,personal_care,1.0,Sophia,Dickson,F,9047 Rodriguez Turnpike,Gibsonville,...,-79.5685,12486,Arboriculturist,2/9/1934,2e4dedc1aee97a9207cc79717c057fa9,1372531055,36.058892,-79.486092,0,18

In [8]:
df.shape

(555719, 23)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  object
 1   cc_num                 555719 non-null  float64
 2   merchant               555719 non-null  object
 3   category               555719 non-null  object
 4   amt                    555719 non-null  float64
 5   first                  555719 non-null  object
 6   last                   555719 non-null  object
 7   gender                 555719 non-null  object
 8   street                 555719 non-null  object
 9   city                   555719 non-null  object
 10  state                  555719 non-null  object
 11  zip                    555719 non-null  int64
 12  lat                    555719 non-null  float64
 13  long                   555719 non-null  float64
 14  city_pop               555719 non-null  int64
 15  job                    555719 non-null  object
 16  dob                    555719 non-null  object
 17  trans_num              555719 non-null  object
 18  unix_time              555719 non-null  int64
 19  merch_lat              555719 non-null  float64
 20  merch_long             555719 non-null  float64
 21  is_fraud               555719 non-null  int64
 22  Hour                   555719 non-null  int64
dtypes: float64(6), int64(5), object(12)
memory usage: 97.5+ MB

In [13]:
df.isnull().sum()

trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
Hour                     0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'Hour'],
      dtype='object')

In [16]:
df['trans_date_trans_time']=pd.to_datetime(df['trans_date_trans_time'])

In [18]:
df['day']=df['trans_date_trans_time'].dt.day

In [24]:
df['hour'] = df['trans_date_trans_time'].dt.hour

In [19]:
df['month']=df['trans_date_trans_time'].dt.month

In [20]:
df['day_name']=df['trans_date_trans_time'].dt.day_name()

In [21]:
df.head(5)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,Hour,day,month,day_name
0,2020-06-22 13:42:00,4.900000e+18,fraud_Johnston-Casper,travel,1.0,Randy,Wood,M,542 Howe Mission Apt. 092,Port Richey,...,10/7/1975,702d4af26c7e9e7311b8f1b774955481,1371908573,28.745893,-83.478989,0,13,22,6,Monday
1,2020-06-22 15:57:00,4.190000e+15,"fraud_Langworth, Boehm and Gulgowski",shopping_net,1.0,Jennifer,Spencer,F,477 Wheeler Burg,Amanda,...,10/3/1992,b468beb46ee3bbebd43e962ecca733d1,1371916667,40.235605,-82.232475,0,15,22,6,Monday
2,2020-06-22 19:49:00,5.710000e+11,"fraud_Kuhic, Bins and Pfeffer",shopping_net,1.0,Barbara,Taylor,F,0069 Robin Brooks Apt. 695,Elberta,...,7/12/1995,0e5e5a49757d0804c928da89403ad8b3,1371930559,44.717170,-86.940090,0,19,22,6,Monday
3,2020-06-29 14:31:00,4.560000e+18,fraud_Gerlach Inc,shopping_net,1.0,Stacy,Villegas,F,20581 Pena Walks,Colorado Springs,...,5/9/1992,3b5f03ac38b6257566e31957f3f959ea,1372516297,38.037407,-105.247202,0,14,29,6,Monday
4,2020-06-29 18:37:00,3.400000e+14,fraud_Rolfson-Kunde,personal_care,1.0,Sophia,Dickson,F,9047 Rodriguez Turnpike,Gibsonville,...,2/9/1934,2e4dedc1aee97a9207cc79717c057fa9,1372531055,36.058892,-79.486092,0,18,29,6,Monday

In [22]:
df['high_amount']=df['amt']>df['amt'].quantile(0.95)

In [25]:
df['is_night']=df['hour'].between(0,5)

In [26]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'Hour', 'day', 'month', 'day_name',
       'high_amount', 'hour', 'is_night'],
      dtype='object')

In [27]:
df[['Hour', 'hour']].head()

   Hour  hour
0    13    13
1    15    15
2    19    19
3    14    14
4    18    18

In [28]:
df = df.drop(['Hour'], axis=1)

In [29]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'day', 'month', 'day_name', 'high_amount',
       'hour', 'is_night'],
      dtype='object')

In [30]:
df['amount_bucket']=pd.cut(df['amt'],
                          bins=[0,50,200,500,1000,5000,100000],
                          labels=['Very Low','Low','Medium','High','Very High','Extreme'])

In [31]:
df['fraud_status']=df['is_fraud'].map({0:'Normal',1:'fraud'})

In [32]:
df.head(10)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,merch_long,is_fraud,day,month,day_name,high_amount,hour,is_night,amount_bucket,fraud_status
0,2020-06-22 13:42:00,4.900000e+18,fraud_Johnston-Casper,travel,1.0,Randy,Wood,M,542 Howe Mission Apt. 092,Port Richey,...,-83.478989,0,22,6,Monday,False,13,False,Very Low,Normal
1,2020-06-22 15:57:00,4.190000e+15,"fraud_Langworth, Boehm and Gulgowski",shopping_net,1.0,Jennifer,Spencer,F,477 Wheeler Burg,Amanda,...,-82.232475,0,22,6,Monday,False,15,False,Very Low,Normal
2,2020-06-22 19:49:00,5.710000e+11,"fraud_Kuhic, Bins and Pfeffer",shopping_net,1.0,Barbara,Taylor,F,0069 Robin Brooks Apt. 695,Elberta,...,-86.940090,0,22,6,Monday,False,19,False,Very Low,Normal
3,2020-06-29 14:31:00,4.560000e+18,fraud_Gerlach Inc,shopping_net,1.0,Stacy,Villegas,F,20581 Pena Walks,Colorado Springs,...,-105.247202,0,29,6,Monday,False,14,False,Very Low,Normal
4,2020-06-29 18:37:00,3.400000e+14,fraud_Rolfson-Kunde,personal_care,1.0,Sophia,Dickson,F,9047 Rodriguez Turnpike,Gibsonville,...,-79.486092,0,29,6,Monday,False,18,False,Very Low,Normal
5,2020-06-30 01:52:00,3.000000e+13,fraud_Nader-Heller,misc_net,1.0,Curtis,Young,M,4319 Watson Shoals Suite 658,Falconer,...,-80.118618,0,30,6,Tuesday,False,1,True,Very Low,Normal
6,2020-06-30 12:08:00,3.850000e+13,fraud_Towne LLC,misc_pos,1.0,Laura,Johns,F,95835 Garcia Rue,Arcadia,...,-82.557933,0,30,6,Tuesday,False,12,False,Very Low,Normal
7,2020-07-03 21:52:00,6.300000e+11,"fraud_Kunze, Larkin and Mayert",travel,1.0,Rachel,Daniels,F,561 Little Plain Apt. 738,Wetmore,...,-86.072975,0,3,7,Friday,False,21,False,Very Low,Normal
8,2020-07-06 06:27:00,4.620000e+12,fraud_Kuhn LLC,shopping_pos,1.0,Vincent,Waller,M,9379 Vanessa Run Apt. 400,Lohrville,...,-94.346716,0,6,7,Monday,False,6,False,Very Low,Normal
9,2020-07-07 15:52:00,4.560000e+15,"fraud_Baumbach, Hodkiewicz and Walsh",shopping_pos,1.0,Pamela,Lewis,F,653 Jessica Extension Apt. 668,Clifton,...,-81.144084,0,7,7,Tuesday,False,15,False,Very Low,Normal

In [33]:
df.to_csv(r"C:\Data\fraudTest.csv\CleaningFraudTestData.csv",index=False)